/*
 * Program: Sum of Numbers Using a While Loop
 *
 * Description:
 * This program accepts a starting number from the user and calculates
 * the sum of 50 numbers generated by increasing the number by 10
 * after each iteration.
 *
 * The program demonstrates:
 * - Taking user input using Scanner.
 * - Using a while loop for repeated execution.
 * - Updating a value by a fixed increment.
 * - Accumulating values using a sum variable.
 */

import java.util.*;

class whi_loop
{
    // Calculates the sum of 50 numbers using a while loop.
    static void loop(Scanner lc)
    {
        int sum = 0;

        // Read the starting number from the user.
        System.out.println("Enter the digit");
        int d = lc.nextInt();

        int i = 1;

        // Repeat the process 50 times.
        while(i <= 50)
        {
            // Add the current number to the total sum.
            sum += d;

            // Increase the number by 10 for the next iteration.
            d += 10;

            // Move to the next iteration.
            i++;
        }

        // Display the calculated sum.
        System.out.println("Sum of the nos is = " + sum);
    }
}

public class WHILE_LOOP
{
    public static void main(String[] loo)
    {
        // Create a Scanner object to accept user input.
        Scanner sc = new Scanner(System.in);

        // Pass the Scanner object to the loop() method.
        whi_loop.loop(sc);
    }
}